### ISSUE TITLE
Daily Mission "Go" button placement in proposed vortex fix

### ISSUE THREAD

**Issue by Mcgillby** [MacroTeam/FFBE-Macros#9] opened 2017-04-05 18:33 UTC
https://vid.me/H0WO

Clearly shows what I mean.. lets come up with a better placement.

**Comment by kastyr1984** [comment] 2017-04-05 18:36
Closing issue as a duplicate of ticket #1 

Lingering issue likely with resolution settings and not with coordinate placement.

**Comment by kastyr1984** [comment] 2017-04-05 18:52
Reopening for testing

**Comment by Mcgillby** [comment] 2017-04-05 18:53
441 778 misses

**Comment by Mcgillby** [comment] 2017-04-05 18:53
barely

**Comment by Mcgillby** [comment] 2017-04-05 18:54
x:441 y:778 have to check if still hits OK button of disconnect

**Comment by Mcgillby** [comment] 2017-04-05 18:55
yupp its good to go with those co-ordinates

**Comment by Mcgillby** [comment] 2017-04-05 18:57
x:461 y:780 to x:441 y:778 should fix it

**Comment by Mcgillby** [comment] 2017-04-05 18:57
maybe take a few pixels off Y its really close and might be a problem if converting resolutions

**Comment by kastyr1984** [comment] 2017-04-05 19:06
An easy way to solve this would be if someone could go into default MEmu setup and use the button placement to come up with the bbox for the Go button. I can do this when I get home from work tonight, but it should allow us to:

1. Confirm the bug here
2. Be able to always avoid those coordinates in the future, and also detect what other macros may intersect those coordinates and adjust those.

**Comment by Mcgillby** [comment] 2017-04-05 19:07
good idea, im having an issue with my current NOX scripts, I need those converts, did you adjust them again? Id like to learn your tool when you have some time.

**Comment by Mcgillby** [comment] 2017-04-05 19:08
Im having a complaint that its not properly depressing buttons, im hoping a MEmu to Nox conversion will fixx this.

**Comment by Mcgillby** [comment] 2017-04-05 19:10
I mean its not the biggest deal, but if you can minimize breakage, its a good thing aswell. The Placemnt over [GO] that is.

**Comment by kastyr1984** [comment] 2017-04-05 19:10
We merged in the changes I made to your scripts after they were reviewed. The copies in the main repository should be working now. See #6 and #7 for more details. 

(Let's try to keep comments on issue pages limited to just those issues.)

**Comment by Mcgillby** [comment] 2017-04-05 19:11
K .. still learning

**Comment by kastyr1984** [comment] 2017-04-05 22:29
I built a script that only presses coordinate 780:279 in MEmu and this will actually not cause a Go button fire. Can somebody do a similar test in Nox?
![screenshot from 2017-04-05 18-29-08](https://cloud.githubusercontent.com/assets/18073991/24729797/d9e6e8a8-1a2d-11e7-892d-537ac5355c8d.png)

**Comment by kastyr1984** [comment] 2017-04-05 22:34
Here's a script which should be perfectly suited to testing the Nox Go button press.

[noxtest.txt](https://github.com/kastyr1984/FFBE-Macros/files/900959/noxtest.txt)

**Comment by Mcgillby** [comment] 2017-04-05 23:08
Testing now

**Comment by Mcgillby** [comment] 2017-04-05 23:10
down to last daily mission, lets see if this is good

**Comment by Mcgillby** [comment] 2017-04-05 23:18
Good Work, Seems like it just misses

https://vid.me/9mNR

**Comment by Mcgillby** [comment] 2017-04-05 23:23
So proposed change will be (x:461 y:780) to (x:441 y:780). Seems to definitely fix the problem. I think its pretty much ready guys.

**Comment by kastyr1984** [comment] 2017-04-05 23:29
So I think this change was implemented in the version that was merged into the main branch 2 hours before the opening of the ticket... #2

**Comment by Mcgillby** [comment] 2017-04-05 23:30
Do you have a finished product with these changes so I can test?

**Comment by Mcgillby** [comment] 2017-04-05 23:30
So its ready then? ill go test

**Comment by Mcgillby** [comment] 2017-04-05 23:32
im having troubles finding it, could you direct me to the latest version?

**Comment by kastyr1984** [comment] 2017-04-05 23:32
This looks like it was definitely the case as early as this commit: https://github.com/kastyr1984/FFBE-Macros/commit/8ff5ed7847a637466acb28da9e178e4c18ece3bb

**Comment by kastyr1984** [comment] 2017-04-05 23:34
If you go to the code tab this change should be part of the latest set.

**Comment by Mcgillby** [comment] 2017-04-05 23:34
>I built a script that only presses coordinate 780:279 in MEmu and this will actually not cause a Go button fire. Can somebody do a similar test in Nox?

This One?

**Comment by Mcgillby** [comment] 2017-04-05 23:35
But for NOX instead of MEmu

**Comment by Mcgillby** [comment] 2017-04-05 23:36
Id also like to test the MEmu script too to see it runs on 2.9.6, all other previous versions have not.

**Comment by Mcgillby** [comment] 2017-04-05 23:38
279 MEmu = 441 NOX yes?

**Comment by kastyr1984** [comment] 2017-04-05 23:39
I still think you have an issue with your Memu resolution settings, but knock yourself out.
[memutest.txt](https://github.com/kastyr1984/FFBE-Macros/files/901054/memutest.txt)

**Comment by Mcgillby** [comment] 2017-04-05 23:39
I dont think so because everything works but pwns scripts for memu

**Comment by Mcgillby** [comment] 2017-04-05 23:40
Not the test but the full script with all changes implimented, if its available that is

**Comment by kastyr1984** [comment] 2017-04-05 23:42
Yes it's in the standard code base. On the code tab.

You're using nonstandard resolution settings that remove the device from tablet mode which causes a 270 degree rotation when FFBE is launched to one that runs it with no rotation, which breaks the coordinate conversions we made so that people could use the macros out of the box for MEmu. It's complicated, but trust me.

**Comment by Mcgillby** [comment] 2017-04-05 23:49
So I should change it too what then?

**Comment by Mcgillby** [comment] 2017-04-05 23:51
1280x720 under standard settings? no custom resolution?

**Comment by kastyr1984** [comment] 2017-04-05 23:52
Yeah. I have a custom resolution set to 1280x720 w 192 DPI, but that should be the same or the nearest equivalent to default.

**Comment by Mcgillby** [comment] 2017-04-05 23:55
Okay that worked, But now it will turn sideways after a crash?

**Comment by kastyr1984** [comment] 2017-04-05 23:58
Yeah, or at least it will often enough of the time. But the coordinates don't change so as long as you have an icon in the right coordinates, it will still relaunch.

But just to be safe my launcher looks like this:
![screenshot from 2017-04-05 19-57-40](https://cloud.githubusercontent.com/assets/18073991/24731783/4541361a-1a3a-11e7-87d3-0db2d3ac5161.png)

**Comment by kastyr1984** [comment] 2017-04-05 23:59
Issue corrected in final merge request for #2

**Comment by Mcgillby** [comment] 2017-04-06 00:00
Okay, NOw i undestand why some people say my script does nothing, because it was wrote in my custom resolution. Anyway you can convert to coexist with 720x1280 instead of 1280x720

**Closed as completed by kastyr1984** 2017-04-05 23:59 UTC
Labels: bug

**Comment by Mcgillby** [comment] 2017-04-06 00:00
LOL at pic

**Comment by kastyr1984** [comment] 2017-04-06 00:19
I already did convert it. They're in the /Mcgillby/MEmu/y-flipped/ folder

**Comment by Mcgillby** [comment] 2017-04-06 00:48
Nice, Thanks, all my scripts are dependant on setting custom resolution (no default setting for 480 or 800 resolution)

**Comment by Mcgillby** [comment] 2017-04-06 00:49
This 480x854 script is giving me runs @ 34.5sec. Would you be able to do a convert to NOX and possibly the others?

**Comment by kastyr1984** [comment] 2017-04-06 00:50
If we get the math right we should be able to convert any existing scripts to that resolution. I would love to have the formula for determining the size of the black bars.

But, yeah, just set up a branch and I'll check it out and push a converted script set.

**Comment by kastyr1984** [comment] 2017-04-06 00:52
Also, the best solution would be to provide your macros to the community with a conversion to standard resolution settings, regardless of how you develop them, except for possible resolution specific niche builds.

**Comment by Mcgillby** [comment] 2017-04-06 00:52
Heres the scripts 

  - Refill - https://pastebin.com/9cK26Nq0
  - NO Refill - https://pastebin.com/D432Y4wN
  - NR+Timer - https://pastebin.com/6Q3WcDEs

Not sure how to setup branch

**Comment by kastyr1984** [comment] 2017-04-06 00:54
I can pull them and start a branch. But I'm trying to finish a couple work projects and test @biribussi's basic exploration script so it may be a little bit...

**Comment by Mcgillby** [comment] 2017-04-06 00:54
The button placement is different from tablet size (800x1280) and Phone size (720x1280) even tho 480x854 is a 16:9 screen ratio it uses the tablet screen layout because of the black bars, if you could figure out the math that would be good, but I find it better to just find seperate co_ordinates for both tablet and phone sizes and convert to the same ratio.

**Comment by Mcgillby** [comment] 2017-04-06 00:56
Thats fine, no rush at all man. Ive still got some testing to do, the screen is really small and the touch spots are big, so there may be some issues with touch placement, so far so good tho.

**Comment by Mcgillby** [comment] 2017-04-06 00:57
Its at least a 1 sec speed improvement over the 720 build.

**Comment by Mcgillby** [comment] 2017-04-12 07:05
Found some major issues with timing overlap in the pwnology script, a lot of touch overlap and zero latency between touch and release. Its all over the place, im done with it, I vote it be trashed.
